server:
  port: 8081

spring:
  application:
    name: resource-server-demo
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.tu-dominio.com

app:
  security:
    audience: https://api.tu-dominio.com

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
